server:
  port: 8081
spring:
  application:
    name: fraud
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      refresh:
        enabled: true
      probability: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers:
      - http://localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      retries: 0
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties: spring.json.type.mapping.event:com.ab.fraud.event.FraudCheckEvent
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka